sudo: false

language: java

cache:

  directories:

  - "$HOME/.cache"

before_install:

  - cp .travis.settings.xml $HOME/.m2/settings.xml

deploy:

  provider: script

  script: "mvn clean package"

  skip_cleanup: false
